language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql
      php: 5.3
    - env: DBTYPE=sqlite
      php: 5.4
    - env: DBTYPE=mysql
      php: 5.5
    - env: DBTYPE=sqlite
      php: 5.6
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DBTYPE=sqlite

before_script:
  - composer self-update
  - bash .travis.sh

script:
  - cd ../phase3/tests/phpunit
  - ./phpunit.php -c ../../extensions/WikibaseQuery/phpunit.xml.dist  --exclude-group SimpleQueryTest --use-normal-tables

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
